# -*- coding: utf-8 -*-
"""DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gopd0uLfF7votq0UfF3T-Kc8HnZBvCi8
"""

import pandas as pd
lst=['Greek','for','greek','is','portal','for','greek']
df=pd.DataFrame(lst)
print(df)

import pandas as pd
data={'Name':['Tom','nick','krish','jack'],
      'Age':[20,21,19,19]}
df=pd.DataFrame(data)
print(df)

import pandas as pd

df = pd.read_csv("data.csv")

numeric_cols = df.select_dtypes(include="number")

print("Mean:\n", numeric_cols.mean())
print("\nMedian:\n", numeric_cols.median())
print("\nMode:\n", numeric_cols.mode().iloc[0])
print("\nVariance:\n", numeric_cols.var())
print("\nStandard Deviation:\n", numeric_cols.std())

import numpy as np

arr = df[["age","sales","a","b"]].to_numpy()

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))

# Reshape example (5x4 -> 4x5)
reshaped = arr.reshape(4,5)
print("Reshaped:\n", reshaped)

# Element-wise multiplication (multiply by 2)
print("Element-wise multiplication:\n", arr * 2)

A = df[["a","b"]].to_numpy()
B = df[["a","b"]].to_numpy()

# Addition
print("Addition:\n", A + B)

# Subtraction
print("Subtraction:\n", A - B)

# Matrix multiplication
print("Matrix multiplication:\n", np.dot(A.T, B))

# Transpose
print("Transpose of A:\n", A.T)

random_arr = np.random.rand(10)

print("Mean:", np.mean(random_arr))
print("Standard deviation:", np.std(random_arr))
print("Minimum:", np.min(random_arr))
print("Maximum:", np.max(random_arr))

from scipy import stats

sales = df["sales"].to_numpy()

print("Mean using scipy:", stats.tmean(sales))

# Test if average sales = 200
t_stat, p_value = stats.ttest_1samp(sales, 200)

print("T-statistic:", t_stat)
print("P-value:", p_value)

import numpy as np
from scipy import integrate

# Define function
def f(x):
    return x**2

# Definite integration from 0 to 5
result, error = integrate.quad(f, 0, 5)

print("Integration Result:", result)
print("Estimated Error:", error)

from scipy import optimize

# Define function
def f(x):
    return x**2 + 4*x + 4

# Initial guess
initial_guess = 0

# Minimize
result = optimize.minimize(f, initial_guess)

print("Minimum x:", result.x[0])
print("Minimum value:", result.fun)